modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Create-In-Locomotion/Create-Escalated/issues"
license = "MIT"

[[mods]]
modId = "escalated"
version = "${mod_version}"
displayName = "Create: Escalated"
authors = "rbasamoyai"
description = """Bringing you to higher places in your Create mod builds
Attributions:
Logo by LopyLuna
Textures and models by rbasamoyai
"""
logoFile = "icon.png"

[[dependencies.escalated]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.escalated]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.escalated]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.escalated]]
modId = "sable"
type = "optional"
versionRange = "[${sable_version_range},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "escalated.mixins.json"